print("String by DEveloper")
data = "Developer"
print(len(data))
print(type(data))
print(data[1])
print(data[2:])
print(data[2:4])
print(data[:2])
print(data.upper())
print(data.lower())
print(data.replace("developer", "Syab Ahmad de Developer"))
print(data)